// ignore_for_file: implementation_imports

import 'dart:io';

import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import 'package:build_runner/src/internal.dart';

class FastBootstrapGenerator {
  Future<void> generate({
    required String projectDirectory,
    required String outputPath,
    required String internalLibraryPath,
    required String upstreamCommit,
  }) async {
    final builderFactoriesExpressions = await _withWorkingDirectory(
      projectDirectory,
      () => loadBuilderFactories(workspace: false),
    );
    final internalImport = _relativeImport(
      fromFile: outputPath,
      toFile: internalLibraryPath,
    );

    final library = Library(
      (builder) => builder.body.addAll([
        declareFinal('_builderFactories')
            .assign(
              refer(
                'BuilderFactories',
                'package:build_runner/src/build_plan/builder_factories.dart',
              ).call(
                [literalMap(builderFactoriesExpressions.builderFactories)],
                {
                  'postProcessBuilderFactories': literalMap(
                    builderFactoriesExpressions.postProcessBuilderFactories,
                  ),
                },
              ),
            )
            .statement,
        _main(internalImport),
      ]),
    );

    final emitter = DartEmitter(
      allocator: Allocator.simplePrefixing(),
      useNullSafetySyntax: true,
    );
    final formatted =
        DartFormatter(
          languageVersion: DartFormatter.latestLanguageVersion,
        ).format('''
// ignore_for_file: directives_ordering
// Generated by fast_build_runner bootstrap spike.
// Pinned build_runner commit: $upstreamCommit
${library.accept(emitter)}
''');
    final file = File(outputPath)..createSync(recursive: true);
    file.writeAsStringSync(formatted);
  }

  Method _main(String internalImport) => Method((builder) {
    builder
      ..name = 'main'
      ..modifier = MethodModifier.async
      ..returns = refer('Future<void>')
      ..requiredParameters.add(
        Parameter(
          (builder) => builder
            ..name = 'args'
            ..type = TypeReference(
              (builder) => builder
                ..symbol = 'List'
                ..types.add(refer('String')),
            ),
        ),
      )
      ..body = refer('FastSpikeChildRunner', internalImport)
          .newInstance([])
          .property('run')
          .call([refer('args'), refer('_builderFactories')])
          .awaited
          .statement;
  });

  Future<T> _withWorkingDirectory<T>(
    String directory,
    Future<T> Function() action,
  ) async {
    final previous = Directory.current;
    Directory.current = directory;
    try {
      return await action();
    } finally {
      Directory.current = previous;
    }
  }

  String _relativeImport({required String fromFile, required String toFile}) {
    return p.relative(toFile, from: p.dirname(fromFile)).replaceAll(r'\', '/');
  }
}
